---
apiVersion: v1
baseDomain: haist.farm
metadata:
  name: overwatch
compute:
- name: worker
  replicas: 0
controlPlane:
  name: master
  replicas: 3
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: '{"auths":{"fake":{"auth":"ZmFrZTpmYWtl"}}}'
sshKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOaasdPoVflRj8musM9BBmsH1fHLuZypmq3zwCuPjSfw haist@208PC001'
